# Site settings
name: 艾翁的博客
email: long798266215@163.com
author: Ivern
url: https://aiweng.github.io/
resume_site: https://aiweng.github.io/
github: https://aiweng.github.io/
baseurl: ""  #根目录
description: 快乐工作，认真生活。
motto: The best preparation for tomorrow is doing your best today
banner: 我想带你去看绚丽的山峦，去看秀丽的溪谷，这份心情，人类是如何称呼的呢。
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: maoxiaoke
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : xiaokedada
